# -*- coding: utf-8 -*-
"""convert_csv_to_json.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195X51O9UdS6OYBJwvTxMHqZIJpt5kfRC
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pymongo
from pymongo import MongoClient
client = MongoClient('localhost', 27017)
# Choose or create a database
db = client['PSUTBOT_database_1']

import pandas as pd
import json

def convert_csv_to_json(csv_file_path, json_file_path):
    """
    Convert a CSV file to JSON.

    Parameters:
        csv_file_path (str): Path to the CSV file.
        json_file_path (str): Path to save the JSON file.
    """
    # Read the CSV file into a pandas DataFrame
    df = pd.read_csv(csv_file_path)

    # Convert the DataFrame to JSON (records format)
    json_data = df.to_json(orient='records', lines=True)

    # Specify the output JSON file path
    with open(json_file_path, 'w', encoding='utf-8') as json_file:
        json_file.write(json_data)

    print(f'Data saved to: {json_file_path}')

