# -*- coding: utf-8 -*-
"""insert_office_hours_to_mongodb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195X51O9UdS6OYBJwvTxMHqZIJpt5kfRC
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pymongo
from pymongo import MongoClient
client = MongoClient('localhost', 27017)
# Choose or create a database
db = client['PSUTBOT_database_1']

def insert_office_hours_to_mongodb(json_file_path, db, collection_name):
    """
    Insert JSON data into MongoDB.

    Parameters:
        json_file_path (str): Path to the JSON file.
        db: MongoDB database object.
        collection_name (str): Name of the collection to insert data into.
    """
    # Create a collection
    collection_off_hr = db['office_hours']

    # Load the JSON data from the file and insert each line separately into MongoDB
    with open(json_file_path, 'r', encoding='utf-8') as file:
        for line in file:
            json_data = json.loads(line)

            # Insert JSON data into MongoDB
            collection.insert_one(json_data)

    print("Data inserted successfully into MongoDB!")

# Example usage
csv_file_path = r'C:\Users\BASIL\Desktop\Office hours.csv'
json_file_path = r'C:\Users\BASIL\Desktop\Office_hours.json'
collection_name_off_hr = 'office_hours'  # Update with your actual collection name

# Convert CSV to JSON
convert_csv_to_json(csv_file_path, json_file_path)

# Insert JSON data into MongoDB
insert_office_hours_to_mongodb(json_file_path, db, collection_name_off_hr)

