# -*- coding: utf-8 -*-
"""insert_school_info_to_mongodb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195X51O9UdS6OYBJwvTxMHqZIJpt5kfRC
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pymongo
from pymongo import MongoClient
client = MongoClient('localhost', 27017)
# Choose or create a database
db = client['PSUTBOT_database_1']

def insert_school_info_to_mongodb(data, db, collection_name):
    """
    Inserts school information into MongoDB.

    Parameters:
        data (dict): School information data dictionary.
        db: MongoDB database object.
        collection_name (str): Name of the collection to insert data into.
    """
    # Create a collection

    collection_school_info = db['school information']

    # Insert JSON data into MongoDB
    collection_school_info.insert_one(data)

    print("Data inserted successfully!")

# Example usage

collection_name_school = 'school_information'  # Update with your actual collection name

# Load the JSON data from the file
with open(json_file_path_all_data, 'r', encoding='utf-8') as file:
    all_data = json.load(file)

# Iterate over each URL's data and insert into MongoDB
for url, data_for_url in all_data.items():
    print(f"Inserting data for URL: {url}")
    # Call the function to insert data into MongoDB
    insert_school_info_to_mongodb(data_for_url, db, collection_name_school)

print("All data inserted successfully into MongoDB!")