# -*- coding: utf-8 -*-
"""def insert_student_life_activities_to_mongodb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195X51O9UdS6OYBJwvTxMHqZIJpt5kfRC
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pymongo
from pymongo import MongoClient
client = MongoClient('localhost', 27017)
# Choose or create a database
db = client['PSUTBOT_database_1']

def insert_student_life_activities_to_mongodb(data, db, collection_name):
    """
    Inserts student life activities information into MongoDB.

    Parameters:
        data (dict): Student life activities information data dictionary.
        db: MongoDB database object.
        collection_name (str): Name of the collection to insert data into.
    """
    # Create a collection
    collection_event = db['Events']

    # Convert the dictionary to a list of documents
    documents = [{"event_name": name, "event_description": description} for name, description in zip(data["event_name"], data["event_description"])]

    # Insert JSON data into MongoDB
    collection_event.insert_many(documents)

    print("Data inserted successfully!")

# Example usage
url_student_life_activities = "https://psut.edu.jo/en/student-life-activities"
result_event_data = scrape_student_life_activities(url_student_life_activities)

# Check if the result_event_data is not None
if result_event_data is not None:
    collection_name_events = 'student_life_activities'  # Update with your actual collection name
    insert_student_life_activities_to_mongodb(result_event_data, db, collection_name_events)
else:
    print("No data to insert.")
